name: "Build & Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: "Execute build"
        run: |
          npm ci
          npm run build
      
      # Temporarily disabling tests until the workflow setup is sorted. Please reactivate when ready.
      # - name: "Execute tests"
      #   run: npm test
