name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  
  staging-deploy:
    name: "Cloudflare - Staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://auth0-service-staging.cheqd.net/

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: "staging"
          wranglerVersion: '2.0.27'
          preCommands: npm ci
          command: publish --env staging
          secrets: |
            AUTH0_DOMAIN
            AUTH0_CLIENT_ID
            AUTH0_REDIRECT_URI
            AUTH0_URI
            TWITTER_FETCH_USER_URI
            TWITTER_BEARER_TOKEN
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_REDIRECT_URI: ${{ secrets.AUTH0_REDIRECT_URI }}
          AUTH0_URI: ${{ secrets.AUTH0_URI }}
          TWITTER_FETCH_USER_URI: ${{ secrets.TWITTER_FETCH_USER_URI }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

  production-deploy:
    name: "Cloudflare - Production"
    needs: staging-deploy
    if: ${{ success() && ( github.ref_name == 'main' ) }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://auth0-service.cheqd.net/

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '2.0.27'
          preCommands: npm ci
          command: publish
          secrets: |
            AUTH0_DOMAIN
            AUTH0_CLIENT_ID
            AUTH0_REDIRECT_URI
            AUTH0_URI
            TWITTER_FETCH_USER_URI
            TWITTER_BEARER_TOKEN
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_REDIRECT_URI: ${{ secrets.AUTH0_REDIRECT_URI }}
          AUTH0_URI: ${{ secrets.AUTH0_URI }}
          TWITTER_FETCH_USER_URI: ${{ secrets.TWITTER_FETCH_USER_URI }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
